[mcp_servers.neon]
type = "http"
url = "https://mcp.neon.tech/mcp"


[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp","--api-key", "ctx7sk-f1160e9a-be03-4d3b-aa9c-9e05d4c0b987"]
startup_timeout_sec = 20
tool_timeout_sec = 60
enabled = true