// Mock data for dashboard UI - single source of truth until database is implemented

export const mockUser = {
  id: "user-1",
  email: "alex@devstash.io",
  name: "Alex Chen",
  image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
  plan: "PRO" as const,
};

export const mockItemTypes = [
  {
    id: "type-1",
    name: "Snippet",
    slug: "snippet",
    icon: "Code2",
    color: "blue",
    isSystem: true,
  },
  {
    id: "type-2",
    name: "Prompt",
    slug: "prompt",
    icon: "Sparkles",
    color: "purple",
    isSystem: true,
  },
  {
    id: "type-3",
    name: "Note",
    slug: "note",
    icon: "FileText",
    color: "zinc",
    isSystem: true,
  },
  {
    id: "type-4",
    name: "Command",
    slug: "command",
    icon: "Terminal",
    color: "green",
    isSystem: true,
  },
  {
    id: "type-5",
    name: "File",
    slug: "file",
    icon: "File",
    color: "orange",
    isSystem: true,
  },
  {
    id: "type-6",
    name: "Image",
    slug: "image",
    icon: "Image",
    color: "pink",
    isSystem: true,
  },
  {
    id: "type-7",
    name: "URL",
    slug: "url",
    icon: "Link",
    color: "cyan",
    isSystem: true,
  },
];

export const mockCollections = [
  {
    id: "col-1",
    name: "React Patterns",
    slug: "react-patterns",
    description: "Common React patterns and best practices",
    isFavorite: true,
    itemCount: 8,
  },
  {
    id: "col-2",
    name: "AI Prompts",
    slug: "ai-prompts",
    description: "Useful prompts for coding assistance",
    isFavorite: false,
    itemCount: 12,
  },
  {
    id: "col-3",
    name: "CLI Commands",
    slug: "cli-commands",
    description: "Frequently used terminal commands",
    isFavorite: false,
    itemCount: 15,
  },
  {
    id: "col-4",
    name: "Project Templates",
    slug: "project-templates",
    description: "Boilerplate code and starter files",
    isFavorite: true,
    itemCount: 6,
  },
  {
    id: "col-5",
    name: "Learning Resources",
    slug: "learning-resources",
    description: "Tutorials, docs, and references",
    isFavorite: false,
    itemCount: 20,
  },
];

export const mockItems = [
  {
    id: "item-1",
    title: "useDebounce Hook",
    description: "Custom hook for debouncing values in React",
    typeId: "type-1",
    collectionId: "col-1",
    content: "const useDebounce = (value, delay) => { ... }",
    language: "typescript",
    isFavorite: true,
    isPinned: true,
    tags: ["react", "typescript"],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "item-2",
    title: "Code Review Prompt",
    description: "Comprehensive code review assistant prompt",
    typeId: "type-2",
    collectionId: "col-2",
    content:
      "Review this code for bugs, security issues, and best practices...",
    isFavorite: true,
    isPinned: false,
    tags: ["debugging", "review"],
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "item-3",
    title: "Git Rebase Interactive",
    description: "Squash and reorder commits interactively",
    typeId: "type-4",
    collectionId: "col-3",
    content: "git rebase -i HEAD~3",
    language: "bash",
    isFavorite: false,
    isPinned: false,
    tags: ["git"],
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-08"),
  },
  {
    id: "item-4",
    title: "Next.js API Routes Guide",
    description: "Official documentation for Next.js API routes",
    typeId: "type-7",
    collectionId: "col-5",
    url: "https://nextjs.org/docs/app/building-your-application/routing/route-handlers",
    isFavorite: false,
    isPinned: false,
    tags: ["nextjs", "api"],
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "item-5",
    title: "TypeScript Basics",
    description: "Essential TypeScript concepts for beginners",
    typeId: "type-3",
    collectionId: "col-5",
    content: "# TypeScript Basics\n\nTypes, interfaces, generics...",
    isFavorite: false,
    isPinned: false,
    tags: ["typescript", "learning"],
    createdAt: new Date("2024-01-03"),
    updatedAt: new Date("2024-01-03"),
  },
  {
    id: "item-6",
    title: "React Component Template",
    description: "Boilerplate React component with hooks",
    typeId: "type-1",
    collectionId: "col-4",
    content: "export function MyComponent() { ... }",
    language: "typescript",
    isFavorite: false,
    isPinned: false,
    tags: ["react", "template"],
    createdAt: new Date("2024-01-02"),
    updatedAt: new Date("2024-01-02"),
  },
  {
    id: "item-7",
    title: "Node.js Server Setup",
    description: "Express server starter template",
    typeId: "type-1",
    collectionId: "col-4",
    content: "const app = express(); ...",
    language: "javascript",
    isFavorite: false,
    isPinned: false,
    tags: ["nodejs", "backend"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "item-8",
    title: "Docker Compose Config",
    description: "Multi-container Docker setup",
    typeId: "type-5",
    collectionId: null,
    content: "version: '3.9'\nservices:\n  ...",
    isFavorite: false,
    isPinned: false,
    tags: ["docker", "devops"],
    createdAt: new Date("2023-12-30"),
    updatedAt: new Date("2023-12-30"),
  },
  {
    id: "item-9",
    title: "CSS Grid Patterns",
    description: "Responsive grid layouts using CSS",
    typeId: "type-1",
    collectionId: "col-1",
    content: ".grid { display: grid; ... }",
    language: "css",
    isFavorite: false,
    isPinned: false,
    tags: ["css", "layout"],
    createdAt: new Date("2023-12-28"),
    updatedAt: new Date("2023-12-28"),
  },
  {
    id: "item-10",
    title: "API Error Handling",
    description: "Best practices for API error responses",
    typeId: "type-2",
    collectionId: "col-2",
    content: "Error handling strategies for REST APIs...",
    isFavorite: false,
    isPinned: false,
    tags: ["api", "error-handling"],
    createdAt: new Date("2023-12-25"),
    updatedAt: new Date("2023-12-25"),
  },
];
